name: Fehler melden
description: Erstellt eine Mitteilung, um den Fehler zu korrigieren
title: "[BUG]: "
labels: ["bug"]
projects: AlBuSoft/5

body:
  - type: input
    id: title
    attributes:
      label: Titel
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: Beschreibung
    validations:
      required: true

  - type: input
    id: fix
    attributes:
      label: Lösungsvorschlag
    validations:
      required: true
