name: Ein Thema wünschen
description: Erzeugt eine Nachricht zur Eingabe eines neuen Themas
title: "[NEW]: "
labels: ["proposal", "enhancement", "documentation"]
projects: AlBuSoft/5

body:
  - type: input
    id: topic
    attributes:
      label: Thema
#      description: |
      placeholder: |
        Der Name des zu wünschenden Themas.
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Beschreibung
#      description: |
      placeholder: |
        Eine konkrete Beschreibung des Themas.
    validations:
      required: true

  - type: textarea
    id: documentation
    attributes:
      label: Dokumentation
#      description: |
      placeholder: |
        Ggf. eine fertige Dokumentation.
    validations:
      required: false
